Add install tools for tar/gzip portable

diff --git a/tools/install-tar-portable b/tools/install-tar-portable
--- a/tools/install-tar-portable
+++ b/tools/install-tar-portable
@@ -3,9 +3,9 @@
 set -e
 
 BIN_PATH="$1"
-VERSION="v9.0.2094"
+VERSION="1.35"
 VERSION_REPO="v0.0.0"
-BASE_URL="https://github.com/chpock/dotfiles/releases/download/${VERSION_REPO}/vim-portable.${VERSION}."
+BASE_URL="https://github.com/chpock/dotfiles/releases/download/${VERSION_REPO}/tar-portable.${VERSION}."
 SUFFIX="$(cat <<EOF
 GNU_Linux:x86_64
 linux.x86_64
@@ -14,7 +14,7 @@ EOF
 
 # convert to absolute
 BIN_PATH="$(cd "$BIN_PATH"; pwd)"
-BIN="$BIN_PATH/vim-portable"
+BIN="$BIN_PATH/tar-portable"
 
 if [ -x "$BIN" ]; then
     if CUR_VERSION="$("$BIN" --portable-version)"; then
@@ -25,23 +25,22 @@ fi
 
 SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
 if [ -z "$SUFFIX" ]; then
-    echo "$0: Error: unknown platform for vim-portable" >&2
+    echo "$0: Error: unknown platform for tar-portable" >&2
     exit 1
 fi
 
-command -v tar >/dev/null 2>&1 || "$(dirname "$0")/install-tar-portable" "$BIN_PATH"
 command -v gzip >/dev/null 2>&1 || "$(dirname "$0")/install-gzip-portable" "$BIN_PATH"
 
 URL="$BASE_URL$SUFFIX"
 
-echo "Downloading vim-portable version $VERSION ..." >&2
+echo "Downloading tar-portable version $VERSION ..." >&2
 TEMP_DIR="$(mktemp --directory)"
 # run in subshell to preserve pwd
 (
     cd "$TEMP_DIR"
-    curl --silent --fail --show-error -L "$URL" > vim-portable
-    echo "Copying vim-portable to $BIN_PATH ..." >&2
-    mv -f vim-portable "$BIN"
+    curl --silent --fail --show-error -L "$URL" > tar-portable
+    echo "Copying tar-portable to $BIN_PATH ..." >&2
+    mv -f tar-portable "$BIN"
     chmod +x "$BIN"
 )
 
